defaults:
  - exploration_strategy: epsilon-greedy
mem_capacity: 10000
epsilon: 1.0
nn_update: 50
batch_size: 32
learning_rate: 0.00005
learning_rate2: 0.00001
gamma: 0.96
action_count: 3
state_count: 6
continous_ctx_count: 0
discrete_rep_size: 0